### ISSUE TITLE
bufferutil.target.mk:95: recipe for target 'Release/obj.target/bufferutil/src/bufferutil.o' faile d

### ISSUE THREAD

**Issue by amygeorge** [websockets/bufferutil#129]
I'm getting the same error as was addressed in closed issue #22 but I'm getting this error and I've tried installing bufferutil locally and making sure the package-lock files are up-to-date, but I get this error on deployment to heroku. Since the first post was made 5 years ago, I have no idea what could be outdated.

This is what's in the package-lock.json
```

    "bufferutil": {
      "version": "4.0.1",
      "resolved": "https://registry.npmjs.org/bufferutil/-/bufferutil-4.0.1.tgz",
      "integrity": "sha512-xowrxvpxojqkagPcWRQVXZl0YXhRhAtBEIq3VoER1NH5Mw1n1o0ojdspp+GS2J//2gCVyrzQDApQ4unGF+QOoA==",
      "requires": {
        "node-gyp-build": "~3.7.0"
      }

```
and below is the error I get

```
remote:
remote:        > bufferutil@4.0.1 install /tmp/build_b454d817/node_modules/client/node_modules/bufferutil
remote:        > node-gyp-build
remote:
remote:        make: Entering directory '/tmp/build_b454d817/client/node_modules/bufferutil/build'
remote:          CC(target) Release/obj.target/bufferutil/src/bufferutil.o
remote:        ../src/bufferutil.c: In function ‘Init’:
remote:        ../src/bufferutil.c:156:12: error: too many arguments to function ‘napi_create_function’
remote:           status = napi_create_function(env, NULL, 0, Mask, NULL, &mask);
remote:                    ^~~~~~~~~~~~~~~~~~~~
remote:        In file included from ../src/bufferutil.c:3:0:
remote:        /app/.node-gyp/8.2.1/include/node/node_api.h:148:25: note: declared here
remote:         NAPI_EXTERN napi_status napi_create_function(napi_env env,
remote:                                 ^~~~~~~~~~~~~~~~~~~~
remote:        ../src/bufferutil.c:159:12: error: too many arguments to function ‘napi_create_function’
remote:           status = napi_create_function(env, NULL, 0, Unmask, NULL, &unmask);
remote:                    ^~~~~~~~~~~~~~~~~~~~
remote:        In file included from ../src/bufferutil.c:3:0:
remote:        /app/.node-gyp/8.2.1/include/node/node_api.h:148:25: note: declared here
remote:         NAPI_EXTERN napi_status napi_create_function(napi_env env,
remote:                                 ^~~~~~~~~~~~~~~~~~~~
remote:        ../src/bufferutil.c: At top level:
remote:        ../src/bufferutil.c:171:35: warning: initialization from incompatible pointer type [-Wincompatibl
e-pointer-types]
remote:         NAPI_MODULE(NODE_GYP_MODULE_NAME, Init)
remote:                                           ^
remote:        /app/.node-gyp/8.2.1/include/node/node_api.h:92:7: note: in definition of macro ‘NAPI_MODULE_X’
remote:               regfunc,                                                        \
remote:               ^~~~~~~
remote:        ../src/bufferutil.c:171:1: note: in expansion of macro ‘NAPI_MODULE’
remote:         NAPI_MODULE(NODE_GYP_MODULE_NAME, Init)
remote:         ^~~~~~~~~~~
remote:        ../src/bufferutil.c:171:35: note: (near initialization for ‘_module.nm_register_func’)
remote:         NAPI_MODULE(NODE_GYP_MODULE_NAME, Init)
remote:                                           ^
remote:        /app/.node-gyp/8.2.1/include/node/node_api.h:92:7: note: in definition of macro ‘NAPI_MODULE_X’
remote:               regfunc,                                                        \
remote:               ^~~~~~~
remote:        ../src/bufferutil.c:171:1: note: in expansion of macro ‘NAPI_MODULE’
remote:         NAPI_MODULE(NODE_GYP_MODULE_NAME, Init)
remote:         ^~~~~~~~~~~
remote:        bufferutil.target.mk:95: recipe for target 'Release/obj.target/bufferutil/src/bufferutil.o' faile
d
remote:        make: *** [Release/obj.target/bufferutil/src/bufferutil.o] Error 1
remote:        make: Leaving directory '/tmp/build_b454d817/client/node_modules/bufferutil/build'
remote:        gyp ERR! build error
remote:        gyp ERR! stack Error: `make` failed with exit code: 2
remote:        gyp ERR! stack     at ChildProcess.onExit (/tmp/build_b454d817/.heroku/node/lib/node_modules/npm/
node_modules/node-gyp/lib/build.js:258:23)
remote:        gyp ERR! stack     at emitTwo (events.js:125:13)
remote:        gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
remote:        gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
remote:        gyp ERR! System Linux 4.4.0-1081-aws
remote:        gyp ERR! command "/tmp/build_b454d817/.heroku/node/bin/node" "/tmp/build_b454d817/.heroku/node/li
b/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
remote:        gyp ERR! cwd /tmp/build_b454d817/client/node_modules/bufferutil
remote:        gyp ERR! node -v v8.2.1
remote:        gyp ERR! node-gyp -v v3.6.2
remote:        gyp ERR! not ok
remote:        npm ERR! code ELIFECYCLE
remote:        npm ERR! errno 1
remote:        npm ERR! bufferutil@4.0.1 install: `node-gyp-build`
remote:        npm ERR! Exit status 1
remote:        npm ERR!
remote:        npm ERR! Failed at the bufferutil@4.0.1 install script.
remote:        npm ERR! This is probably not a problem with npm. There is likely additional logging output above
.
remote:
remote:        npm ERR! A complete log of this run can be found in:
remote:        npm ERR!     /tmp/npmcache.yxTVV/_logs/2020-10-30T20_51_18_375Z-debug.log
remote:
remote: -----> Build failed
```

**Comment by lpinca** [comment]
You need Node.js >= 8.6.0. You version is 8.2.1.

**Comment by amygeorge** [comment]
> You need Node.js >= 8.6.0. Your version is 8.2.1.

That's interesting, when I type node in my terminal it says Welcome to Node.js v12.19.0.

**Comment by eliotstock** [comment]
I have Node.js >= 8.6.0 and I'm still seeing this issue. `npm install` log:

```
0 info it worked if it ends with ok
1 verbose cli [ '/snap/node/2310/bin/node',
1 verbose cli   '/snap/node/2310/bin/npm',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'bufferutil' ]
2 info using npm@6.4.1
3 info using node@v8.16.0
4 verbose npm-session 8f4d94d1061feb61
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 http fetch GET 304 https://registry.npmjs.org/bufferutil 404ms (from cache)
8 http fetch GET 200 https://registry.npmjs.org/bufferutil/-/bufferutil-4.0.3.tgz 12ms (from cache)
9 silly pacote tag manifest for bufferutil@latest fetched in 431ms
10 timing stage:loadCurrentTree Completed in 550ms
11 silly install loadIdealTree
12 silly install cloneCurrentTreeToIdealTree
13 timing stage:loadIdealTree:cloneCurrentTree Completed in 0ms
14 silly install loadShrinkwrap
15 timing stage:loadIdealTree:loadShrinkwrap Completed in 2ms
16 silly install loadAllDepsIntoIdealTree
17 silly resolveWithNewModule bufferutil@4.0.3 checking installable status
18 http fetch GET 304 https://registry.npmjs.org/node-gyp-build 78ms (from cache)
19 silly pacote range manifest for node-gyp-build@^4.2.0 fetched in 81ms
20 silly resolveWithNewModule node-gyp-build@4.2.3 checking installable status
21 timing stage:loadIdealTree:loadAllDepsIntoIdealTree Completed in 92ms
22 timing stage:loadIdealTree Completed in 96ms
23 silly currentTree lib
24 silly idealTree lib
24 silly idealTree └─┬ bufferutil@4.0.3
24 silly idealTree   └── node-gyp-build@4.2.3
25 silly install generateActionsToTake
26 timing stage:generateActionsToTake Completed in 8ms
27 silly diffTrees action count 2
28 silly diffTrees add node-gyp-build@4.2.3
29 silly diffTrees add bufferutil@4.0.3
30 silly decomposeActions action count 16
31 silly decomposeActions fetch node-gyp-build@4.2.3
32 silly decomposeActions extract node-gyp-build@4.2.3
33 silly decomposeActions preinstall node-gyp-build@4.2.3
34 silly decomposeActions build node-gyp-build@4.2.3
35 silly decomposeActions install node-gyp-build@4.2.3
36 silly decomposeActions postinstall node-gyp-build@4.2.3
37 silly decomposeActions finalize node-gyp-build@4.2.3
38 silly decomposeActions refresh-package-json node-gyp-build@4.2.3
39 silly decomposeActions fetch bufferutil@4.0.3
40 silly decomposeActions extract bufferutil@4.0.3
41 silly decomposeActions preinstall bufferutil@4.0.3
42 silly decomposeActions build bufferutil@4.0.3
43 silly decomposeActions install bufferutil@4.0.3
44 silly decomposeActions postinstall bufferutil@4.0.3
45 silly decomposeActions finalize bufferutil@4.0.3
46 silly decomposeActions refresh-package-json bufferutil@4.0.3
47 silly install executeActions
48 silly doSerial global-install 16
49 verbose correctMkdir /root/.npm/_locks correctMkdir not in flight; initializing
50 verbose lock using /root/.npm/_locks/staging-3a08f0df5026584d.lock for /usr/local/lib/node_modules/.staging
51 silly doParallel extract 2
52 silly extract node-gyp-build@4.2.3
53 silly extract bufferutil@4.0.3
54 silly tarball trying node-gyp-build@^4.2.0 by hash: sha512-MN6ZpzmfNCRM+3t57PTJHgHyw/h4OWnZ6mR8P5j/uZtqQr46RRuDE/P+g3n0YR/AiYXeWixZZzaip77gdICfRg==
55 silly tarball trying bufferutil@latest by hash: sha512-yEYTwGndELGvfXsImMBLop58eaGW+YdONi1fNjTINSY98tmMmFijBG6WXgdkfuLNt4imzQNtIE+eBp1PVpMCSw==
56 silly extract node-gyp-build@^4.2.0 extracted to /usr/local/lib/node_modules/.staging/node-gyp-build-54ed72bd (15ms)
57 silly extract bufferutil@latest extracted to /usr/local/lib/node_modules/.staging/bufferutil-295e8daf (19ms)
58 timing action:extract Completed in 22ms
59 silly doReverseSerial unbuild 16
60 silly doSerial remove 16
61 silly doSerial move 16
62 silly doSerial finalize 16
63 silly finalize /usr/local/lib/node_modules/bufferutil/node_modules/node-gyp-build
64 silly finalize /usr/local/lib/node_modules/bufferutil
65 timing action:finalize Completed in 5ms
66 silly doParallel refresh-package-json 2
67 silly refresh-package-json /usr/local/lib/node_modules/bufferutil/node_modules/node-gyp-build
68 silly refresh-package-json /usr/local/lib/node_modules/bufferutil
69 timing action:refresh-package-json Completed in 10ms
70 silly doParallel preinstall 2
71 silly preinstall node-gyp-build@4.2.3
72 info lifecycle node-gyp-build@4.2.3~preinstall: node-gyp-build@4.2.3
73 silly preinstall bufferutil@4.0.3
74 info lifecycle bufferutil@4.0.3~preinstall: bufferutil@4.0.3
75 timing action:preinstall Completed in 1ms
76 silly doSerial build 16
77 silly build node-gyp-build@4.2.3
78 info linkStuff node-gyp-build@4.2.3
79 silly linkStuff node-gyp-build@4.2.3 has /usr/local/lib/node_modules/bufferutil/node_modules as its parent node_modules
80 silly linkStuff node-gyp-build@4.2.3 is part of a global install
81 silly linkStuff node-gyp-build@4.2.3 is installed into a global node_modules
82 verbose linkBins [ { 'node-gyp-build': 'bin.js',
82 verbose linkBins     'node-gyp-build-optional': 'optional.js',
82 verbose linkBins     'node-gyp-build-test': 'build-test.js' },
82 verbose linkBins   '/usr/local/lib/node_modules/bufferutil/node_modules/.bin',
82 verbose linkBins   false ]
83 silly build bufferutil@4.0.3
84 info linkStuff bufferutil@4.0.3
85 silly linkStuff bufferutil@4.0.3 has /usr/local/lib/node_modules as its parent node_modules
86 silly linkStuff bufferutil@4.0.3 is part of a global install
87 silly linkStuff bufferutil@4.0.3 is installed into a global node_modules
88 silly linkStuff bufferutil@4.0.3 is installed into the top-level global node_modules
89 timing action:build Completed in 3ms
90 silly doSerial global-link 16
91 silly doParallel update-linked 0
92 silly doSerial install 16
93 silly install node-gyp-build@4.2.3
94 info lifecycle node-gyp-build@4.2.3~install: node-gyp-build@4.2.3
95 silly install bufferutil@4.0.3
96 info lifecycle bufferutil@4.0.3~install: bufferutil@4.0.3
97 warn lifecycle The node binary used for scripts is /snap/bin/node but npm is using /snap/node/2310/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.
98 verbose lifecycle bufferutil@4.0.3~install: unsafe-perm in lifecycle false
99 verbose lifecycle bufferutil@4.0.3~install: PATH: /snap/node/2310/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/usr/local/lib/node_modules/bufferutil/node_modules/.bin:/usr/local/lib/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
100 verbose lifecycle bufferutil@4.0.3~install: CWD: /usr/local/lib/node_modules/bufferutil
101 silly lifecycle bufferutil@4.0.3~install: Args: [ '-c', 'node-gyp-build' ]
102 silly lifecycle bufferutil@4.0.3~install: Returned: code: 1  signal: null
103 info lifecycle bufferutil@4.0.3~install: Failed to exec install script
104 timing action:install Completed in 31ms
105 verbose unlock done using /root/.npm/_locks/staging-3a08f0df5026584d.lock for /usr/local/lib/node_modules/.staging
106 timing stage:rollbackFailedOptional Completed in 4ms
107 timing stage:runTopLevelLifecycles Completed in 741ms
108 verbose stack Error: bufferutil@4.0.3 install: `node-gyp-build`
108 verbose stack Exit status 1
108 verbose stack     at EventEmitter.<anonymous> (/snap/node/2310/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
108 verbose stack     at emitTwo (events.js:126:13)
108 verbose stack     at EventEmitter.emit (events.js:214:7)
108 verbose stack     at ChildProcess.<anonymous> (/snap/node/2310/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
108 verbose stack     at emitTwo (events.js:126:13)
108 verbose stack     at ChildProcess.emit (events.js:214:7)
108 verbose stack     at maybeClose (internal/child_process.js:915:16)
108 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
109 verbose pkgid bufferutil@4.0.3
110 verbose cwd /home/e/r/eth-metacoin
111 verbose Linux 5.4.0-70-generic
112 verbose argv "/snap/node/2310/bin/node" "/snap/node/2310/bin/npm" "install" "-g" "bufferutil"
113 verbose node v8.16.0
114 verbose npm  v6.4.1
115 error code ELIFECYCLE
116 error errno 1
117 error bufferutil@4.0.3 install: `node-gyp-build`
117 error Exit status 1
118 error Failed at the bufferutil@4.0.3 install script.
118 error This is probably not a problem with npm. There is likely additional logging output above.
119 verbose exit [ 1, true ]
```
