### ISSUE TITLE
Error building package for iOS

### ISSUE THREAD

**Issue by jrmeurer** [websockets/bufferutil#143]
Hitting my head against a wall trying to resolve this build issue. 

I'm trying to build bufferutil as part of `ws` package, for iOS through node-gyp / nodejs-mobile. It seems that the package only installs bindings for MacOS, which causes build failures when building natively for iOS.

I see `'MACOSX_DEPLOYMENT_TARGET': '10.7',` in the binding.gyp file in my nodejs project – when I install this package via react-native, I see `IOS_DEPLOYMENT_TARGET` instead. I'm not sure how to override this setting to IOS instead of Mac. Seems like this is what is causing the issue.

Would love some help :) 

```
GYP_DEFINES="OS=ios" npm i --save --force bufferutil --build-from-source

> bufferutil@4.0.5 install /Users/johnnym/railway-private/nodejs-assets/nodejs-project/node_modules/bufferutil
> node-gyp-build

Debugger attached.
Debugger attached.
  CC(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/bufferutil.node
clang: warning: libstdc++ is deprecated; move to libc++ with a minimum deployment target of OS X 10.9 [-Wdeprecated]
ld: library not found for -lstdc++
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Release/bufferutil.node] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/johnnym/.nvm/versions/node/v8.4.0/lib/node_modules/npm/node_modules/npm-lifecycle/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Darwin 21.1.0
gyp ERR! command "/Users/johnnym/.nvm/versions/node/v8.4.0/lib/node_modules/node/lib/node_modules/node/lib/node_modules/node/lib/node_modules/node/lib/node_modules/node/bin/node" "/Users/johnnym/.nvm/versions/node/v8.4.0/lib/node_modules/npm/node_modules/npm-lifecycle/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/johnnym/railway-private/nodejs-assets/nodejs-project/node_modules/bufferutil
gyp ERR! node -v v12.12.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok

**Comment by lpinca** [comment]
Overriding `MACOSX_DEPLOYMENT_TARGET` seems to work

```
GYP_DEFINES="OS=ios MACOSX_DEPLOYMENT_TARGET=10.9" npx node-gyp -v rebuild
```

Another, possibly better, option is to use the use the specified build settings only when `OS` is `'mac'`:

```diff
diff --git a/binding.gyp b/binding.gyp
index 2b25e54..79c8fa3 100644
--- a/binding.gyp
+++ b/binding.gyp
@@ -4,11 +4,18 @@
       'target_name': 'bufferutil',
       'sources': ['src/bufferutil.c'],
       'cflags': ['-std=c99'],
-      'xcode_settings': {
-        'MACOSX_DEPLOYMENT_TARGET': '10.7',
-        'OTHER_CFLAGS': ['-arch x86_64', '-arch arm64'],
-        'OTHER_LDFLAGS': ['-arch x86_64', '-arch arm64']
-      }
+      'conditions': [
+        [
+          "OS=='mac'",
+          {
+            'xcode_settings': {
+              'MACOSX_DEPLOYMENT_TARGET': '10.7',
+              'OTHER_CFLAGS': ['-arch x86_64', '-arch arm64'],
+              'OTHER_LDFLAGS': ['-arch x86_64', '-arch arm64']
+            }
+          }
+        ]
+      ]
     }
   ]
 }
```
