### ISSUE TITLE
Fails to install on raspberry pi due to missing python2

### ISSUE THREAD

**Issue by bjrne** [websockets/bufferutil#145]
`npm install bufferutil@latest` (which resolves to 4.0.6) does not work for me unfortunately. 

I have a freshly set up raspberry model B with Raspian OS lite, so it's armv6. Thus, the most recent nodejs version is 11.15.0, which is installed. However, python2 is not installed, which leads to the gyp build failing.

Thanks to the hint in the otherwise unrelated #144 that 4.0.4 has certain python deps bundled, I succeeded in installing 4.0.4, so thats a workaround for the meantime, but not great in terms of vulnerabilities.

System info:
```bash
$ npm -v
6.7.0
$ node -v
v11.15.0
$ uname -a
Linux piB 5.15.32+ #1538 Thu Mar 31 19:37:58 BST 2022 armv6l GNU/Linux
```

Complete stacktrace:
```bash
$ npm_config_foreground_scripts=true npm install bufferutil@latest

> bufferutil@4.0.6 install /home/pi/cyp/node_modules/bufferutil
> node-gyp-build

gyp ERR! configure error 
gyp ERR! stack Error: Command failed: /usr/bin/python -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                       ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack 
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:299:12)
gyp ERR! stack     at ChildProcess.emit (events.js:193:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:999:16)
gyp ERR! stack     at Socket.stream.socket.on (internal/child_process.js:403:11)
gyp ERR! stack     at Socket.emit (events.js:193:13)
gyp ERR! stack     at Pipe._handle.close (net.js:614:12)
gyp ERR! System Linux 5.15.32+
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/pi/cyp/node_modules/bufferutil
gyp ERR! node -v v11.15.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.3.2 (node_modules/rollup/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm"})
npm WARN cyp@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bufferutil@4.0.6 install: `node-gyp-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bufferutil@4.0.6 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by lpinca** [comment]
Version 4.0.4 works because there is a bundled prebuilt binary for ARM not because there are special python deps included. In version 4.0.5+ the binary must be compiled. Also Node.js 11 is no longer supported. Did you try to install the module with Node.js 14+? Alternatively try to install `node-gyp@8`.

**Comment by bjrne** [comment]
I didn't know there were unofficial builds for the newer node versions as well for arm. It's now running on NodeJS 16.9 and the install worked fine. Thanks so much for your help and sorry for the erroneous issue!
