### ISSUE TITLE
node-gyp-build issue

### ISSUE THREAD

**Issue by vjgn** [websockets/bufferutil#147]
Hi,

I am running into an issue where bufferutil is triggering node-gyp-build only in certain cases.   
Depending on the source of the packages I get an error in npm-install or no error.   
When using private npm repo, i run into the following error:   
```
gyp ERR! stack Error: Could not find any Python installation to use
gyp ERR! stack     at PythonFinder.fail (/app/bufferutil/bufferutil/node_modules/node-gyp/lib/find-python.js:330:47)
gyp ERR! stack     at PythonFinder.runChecks (/app/bufferutil/bufferutil/node_modules/node-gyp/lib/find-python.js:159:21)
gyp ERR! stack     at PythonFinder.<anonymous> (/app/bufferutil/bufferutil/node_modules/node-gyp/lib/find-python.js:202:16)
gyp ERR! stack     at PythonFinder.execFileCallback (/app/bufferutil/bufferutil/node_modules/node-gyp/lib/find-python.js:294:16)
gyp ERR! stack     at exithandler (node:child_process:395:5)
gyp ERR! stack     at ChildProcess.errorhandler (node:child_process:407:5)
gyp ERR! stack     at ChildProcess.emit (node:events:527:28)
gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:289:12)
gyp ERR! stack     at onErrorNT (node:internal/child_process:476:16)
gyp ERR! stack     at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
gyp ERR! System Linux 4.19.128-microsoft-standard
gyp ERR! command "/usr/local/bin/node" "/app/bufferutil/bufferutil/node_modules/.bin/node-gyp" "rebuild"
gyp ERR! cwd /app/bufferutil/bufferutil
gyp ERR! node -v v18.3.0
gyp ERR! node-gyp -v v9.2.0
gyp ERR! not ok
npm ERR! code 1
npm ERR! path /app/bufferutil/bufferutil
npm ERR! command failed
npm ERR! command sh -c -- node-gyp-build
```

When using public npmjs repo, there is no error at all.   
(To use public npm repo i remove the registry=https://xyz.com line in `.npmrc` file and trigger my pipeline again)

I have verified that the package from private repo is exactly identical to the tarball file from public npmjs repo.

In both cases, I run the npm-install in ci pipeline using node:18-alpine3.14 container.

My questions is, under what condition does node-gyp gets involved during npm-install. From what i understand, if there are prebuilt binaries available then there is no need for node-gyp. But depending on the source of the packages the behavior on the same OS changes.

Debug log when using public npm repo  (only 2 lines found in log that refers to bufferutil):
```
1435 silly fetch manifest bufferutil@^4.0.1
1436 http fetch GET 200 https://registry.npmjs.org/bufferutil 76ms (cache miss)
1437 silly fetch manifest utf-8-validate@^5.0.2
1438 http fetch GET 200 https://registry.npmjs.org/utf-8-validate 88ms (cache miss)
1439 silly placeDep ROOT ws@7.5.9 OK for: express-ws@5.0.2 want: ^7.4.6
```

Debug log when using private npm repo (replaced actual domain with xyz.com):
```
1504 silly fetch manifest bufferutil@^4.0.1
1505 http fetch GET 200 https://xyz.com/artifactory/api/npm/npm/bufferutil 248ms (cache miss)
1506 silly fetch manifest utf-8-validate@^5.0.2
1507 http fetch GET 200 https://xyz.com/artifactory/api/npm/npm/utf-8-validate 132ms (cache miss)
1508 silly placeDep ROOT ws@7.5.9 OK for: express-ws@5.0.2 want: ^7.4.6
1509 silly placeDep ROOT bufferutil@4.0.6 OK for: ws@7.5.9 want: ^4.0.1
1510 silly placeDep ROOT utf-8-validate@5.0.9 OK for: ws@7.5.9 want: ^5.0.2
1511 silly fetch manifest node-gyp-build@^4.3.0
1512 http fetch GET 200 https://xyz.com/artifactory/api/npm/npm/node-gyp-build 131ms (cache miss)
```

Any help in understanding what is happing is greatly appreciated.

**Comment by lpinca** [comment]
> From what i understand, if there are prebuilt binaries available then there is no need for node-gyp.

Correct. I guess that the prebuilt binaries are not found by `node-gyp-build`. I have no idea why. Try to install with the `--verbose` flag to see if an error is logged. See https://github.com/prebuild/node-gyp-build/blob/v4.5.0/bin.js#L10.

**Comment by vjgn** [comment]
@lpinca Thanks for your reply.
I was already running in loglevel=silly mode. I also tried to run it in verbose mode. There was not much additional information.

For the time being, I have added the required build tools to a build stage in my docker file and then copy the node_modules folder over to my final container. 

Do you have any other pointers an what to check?

**Comment by lpinca** [comment]
> I am surprised to see a Microsoft Linux though. My base container is using `FROM node:16-alpine3.14`

Yes, but I guess you are running docker on Windows with WSL.

What happens if you clone the repository, cd into the repository directory, run `npm install`, and then run `npm install` again inside the container? Are binaries built twice?

**Comment by lpinca** [comment]
Also try this with the private npm repo:

1. Clone the repository.
2. Cd into the repository directory.
3. Run `npm install` and `npm run prebuild`.
4. Remove the `build` directory.
5. Apply the following patch

    ```diff
    diff --git a/index.js b/index.js
    index 8c30561..75e49c4 100644
    --- a/index.js
    +++ b/index.js
    @@ -1,7 +1,3 @@
     'use strict';
     
    -try {
    -  module.exports = require('node-gyp-build')(__dirname);
    -} catch (e) {
    -  module.exports = require('./fallback');
    -}
    +module.exports = require('node-gyp-build')(__dirname);
    ```
6. Run `node index.js`.
7. See if an error is thrown.

**Comment by vjgn** [comment]
Thanks for your suggestions. Will try and let you know shortly.

**Comment by vjgn** [comment]
@lpinca I tried the above steps directly in my development computer (Windows 10) using private npm repo. No error was thrown. I am going to try the same in the container now.

**Comment by vjgn** [comment]
@lpinca No error from my linux container also. 

In the first case (directly on my computer) win32-x64 folder. In the later case (in the linux container), prebuild created linux-x64 folder. No error was thrown in both cases when running `node index.js`.

**Comment by lpinca** [comment]
Try to repeat the test using the tarball published on the registry instead of the repository.

```
$ mkdir bufferutil-147
$ cd bufferutil-147/
$ npm pack bufferutil
...
$ tar -xzf bufferutil-4.0.6.tgz
$ cd package/
$ npm install --production
...
$ rm -rf build
$ echo "module.exports = require('node-gyp-build')(__dirname);" > entry.js
$ node entry.js
```

**Comment by vjgn** [comment]
Repeated the steps with the published tarball from the private registry. I don't see any error in this case also.

![image](https://user-images.githubusercontent.com/7349897/196573618-b46b82e9-1183-4a71-8483-051282901d42.png)
