### ISSUE TITLE
Error while installing on Node v5

### ISSUE THREAD

**Issue by artem-malko** [websockets/bufferutil#27]
``` bash
make: Leaving directory `/home/travis/.nvm/versions/node/v5.0.0/lib/node_modules/tars-cli/node_modules/bufferutil/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/travis/.nvm/versions/node/v5.0.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 3.13.0-40-generic
gyp ERR! command "/home/travis/.nvm/versions/node/v5.0.0/bin/node" "/home/travis/.nvm/versions/node/v5.0.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/travis/.nvm/versions/node/v5.0.0/lib/node_modules/tars-cli/node_modules/bufferutil
gyp ERR! node -v v5.0.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
/home/travis/.nvm/versions/node/v5.0.0/lib
└── (empty)
npm ERR! Linux 3.13.0-40-generic
npm ERR! argv "/home/travis/.nvm/versions/node/v5.0.0/bin/node" "/home/travis/.nvm/versions/node/v5.0.0/bin/npm" "install" "-g" "git://github.com/tars/tars-cli.git#0d917536e093a00e3494edf4446b38093ec225a3"
npm ERR! node v5.0.0
npm ERR! npm  v3.3.6
npm ERR! code ELIFECYCLE
npm ERR! bufferutil@1.2.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bufferutil@1.2.1 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the bufferutil package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls bufferutil
npm ERR! There is likely additional logging output above.
npm ERR! Please include the following file with any support request:
npm ERR!     /home/travis/build/tars/tars-cli/npm-debug.log
npm ERR! code 1
```

**Comment by artem-malko** [comment]
There is the link to the build https://travis-ci.org/tars/tars-cli/jobs/88389807

**Comment by spudowiar** [comment]
`redefinition of ‘template<class T> v8::Local<T> _NanEnsureLocal(v8::Local<T>)`

**Comment by harmoney-nikr** [comment]
@artem-malko This seems to be an issue with NPM v3.3.6 which is bundled with Node 5.0.0. A workaround is to `npm install -g npm` (updating to 3.3.10) which allows it to build. 

I'm not sure exactly which version of NPM fixes it, but I presume that the next release of Node will contain at least 3.3.10.

**Comment by artem-malko** [comment]
@harmoney-nikr Thank you, npm 3.3.10 fix it. I think, that it would be useful, if you add this info to readme.md

**Comment by harmoney-nikr** [comment]
@artem-malko I doubt it will be an issue for long as Node versions come out very frequently now. I don't maintain this project, but it probably doesn't need to be added to the readme because it's a very short-term problem.

**Comment by 3rd-Eden** [comment]
Not to mention that 0.5 is an unstable release of node. So things are really expected to break here. Debugging and fixing these bugs are not worth the effort imho

**Comment by harmoney-nikr** [comment]
Node v5.0.0 is a Stable release.

**Comment by ronkorving** [comment]
Indeed. Node v5 is stable, just not LTS.

**Comment by greenify** [comment]
I still have this problem with npm 3.5.0 - has anyone already figured out a proper fix?

**Comment by greenify** [comment]
sorry - apparently this was just a problem with an old version being in the cache :(

**Comment by ZuzooVn** [comment]
I have the same problems with npm 3.5.2

**Comment by MayaLekova** [comment]
Same problem with npm 3.8.1, node-gyp 3.3.0 and node 4.3.1

**Comment by lpinca** [comment]
Closing this as Node 5 is no longer supported.
