### ISSUE TITLE
Error on iojs

### ISSUE THREAD

**Issue by maruf89** [websockets/bufferutil#29]
I tried reinstalling all of my node modules using Node 5.0.0 -> failed 

So I reverted back to my previously working iojs 2.2.1 -> reinstalled -> failed again with 

```
npm install bufferutil                                                              13:29:33

> bufferutil@1.1.0 install /Users/mac/Dropbox/chatter-plot/node_modules/ws/node_modules/bufferutil
> node-gyp rebuild

  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
/Users/mac/Dropbox/chatter-plot/node_modules/.bin/touch: line 1: syntax error near unexpected token `('
/Users/mac/Dropbox/chatter-plot/node_modules/.bin/touch: line 1: `var touch = require("../touch")'
make: *** [Release/obj.target/bufferutil/src/bufferutil.o] Error 2
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:199:12)
gyp ERR! System Darwin 14.3.0
gyp ERR! command "/usr/local/bin/iojs" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/mac/Dropbox/chatter-plot/node_modules/ws/node_modules/bufferutil
gyp ERR! node -v v2.2.1
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
npm WARN install:bufferutil bufferutil@1.1.0 install: `node-gyp rebuild`
npm WARN install:bufferutil Exit status 1

> bufferutil@1.2.1 install /Users/mac/Dropbox/chatter-plot/node_modules/bufferutil
> node-gyp rebuild

  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
/Users/mac/Dropbox/chatter-plot/node_modules/.bin/touch: line 1: syntax error near unexpected token `('
/Users/mac/Dropbox/chatter-plot/node_modules/.bin/touch: line 1: `var touch = require("../touch")'
make: *** [Release/obj.target/bufferutil/src/bufferutil.o] Error 2
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:199:12)
gyp ERR! System Darwin 14.3.0
gyp ERR! command "/usr/local/bin/iojs" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/mac/Dropbox/chatter-plot/node_modules/bufferutil
gyp ERR! node -v v2.2.1
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
nan@1.8.4 node_modules/bufferutil/node_modules/nan -> node_modules/ws/node_modules/nan
npm WARN EPACKAGEJSON chatterplot@1.0.0 No license field.
npm ERR! Darwin 14.3.0
npm ERR! argv "/usr/local/bin/iojs" "/usr/local/bin/npm" "install" "bufferutil"
npm ERR! node v2.2.1
npm ERR! npm  v3.3.6
npm ERR! code ELIFECYCLE
```

**Comment by boiawang** [comment]
same issue

**Comment by mridgway** [comment]
+1

**Comment by lpinca** [comment]
Closing as both iojs and Node 5 are no longer supported. Please comment or reopen if needed.
