### ISSUE TITLE
Failure installing bufferutil on 

### ISSUE THREAD

**Issue by thr0w** [websockets/bufferutil#38]
I tried:
- chmod on `npm config get prefix` to my user
- rm -Rf ~/.node-gyp 

```bash
$ uname -a
Linux server 3.16.0-43-generic #58~14.04.1-Ubuntu SMP Mon Jun 22 10:21:20 UTC 2015 x86_64 
$ node --version
v0.11.13
x86_64 x86_64 GNU/Linux
$ npm --version
1.4.9
$ npm install bufferutil@1.2.1
npm http GET https://registry.npmjs.org/bufferutil
npm http 304 https://registry.npmjs.org/bufferutil
npm http GET https://registry.npmjs.org/bindings
npm http GET https://registry.npmjs.org/nan
npm http 304 https://registry.npmjs.org/bindings
npm http 304 https://registry.npmjs.org/nan

> bufferutil@1.2.1 install /trabalho/este.js/node_modules/bufferutil
> node-gyp rebuild

gyp http GET http://nodejs.org/dist/v0.11.13/node-v0.11.13.tar.gz
gyp http 200 http://nodejs.org/dist/v0.11.13/node-v0.11.13.tar.gz
gyp http GET http://nodejs.org/dist/v0.11.13/SHASUMS.txt
gyp http 200 http://nodejs.org/dist/v0.11.13/SHASUMS.txt
make: Entering directory `/trabalho/este.js/node_modules/bufferutil/build'
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
In file included from ../src/bufferutil.cc:16:0:
../node_modules/nan/nan.h: In function ‘void Nan::SetCounterFunction(v8::CounterLookupCallback)’:
../node_modules/nan/nan.h:459:32: error: ‘class v8::Isolate’ has no member named ‘SetCounterFunction’
     v8::Isolate::GetCurrent()->SetCounterFunction(cb);
                                ^
../node_modules/nan/nan.h: In function ‘void Nan::SetCreateHistogramFunction(v8::CreateHistogramCallback)’:
../node_modules/nan/nan.h:464:32: error: ‘class v8::Isolate’ has no member named ‘SetCreateHistogramFunction’
     v8::Isolate::GetCurrent()->SetCreateHistogramFunction(cb);
                                ^
../node_modules/nan/nan.h: In function ‘void Nan::SetAddHistogramSampleFunction(v8::AddHistogramSampleCallback)’:
../node_modules/nan/nan.h:469:32: error: ‘class v8::Isolate’ has no member named ‘SetAddHistogramSampleFunction’
     v8::Isolate::GetCurrent()->SetAddHistogramSampleFunction(cb);
                                ^
../node_modules/nan/nan.h: In function ‘bool Nan::IdleNotification(int)’:
../node_modules/nan/nan.h:480:39: error: ‘class v8::Isolate’ has no member named ‘IdleNotification’
     return v8::Isolate::GetCurrent()->IdleNotification(idle_time_in_ms);
                                       ^
../node_modules/nan/nan.h: In function ‘void Nan::LowMemoryNotification()’:
../node_modules/nan/nan.h:485:32: error: ‘class v8::Isolate’ has no member named ‘LowMemoryNotification’
     v8::Isolate::GetCurrent()->LowMemoryNotification();
                                ^
../node_modules/nan/nan.h: In function ‘void Nan::ContextDisposedNotification()’:
../node_modules/nan/nan.h:489:32: error: ‘class v8::Isolate’ has no member named ‘ContextDisposedNotification’
     v8::Isolate::GetCurrent()->ContextDisposedNotification();
                                ^
make: *** [Release/obj.target/bufferutil/src/bufferutil.o] Error 1
make: Leaving directory `/trabalho/este.js/node_modules/bufferutil/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1046:12)
gyp ERR! System Linux 3.16.0-43-generic
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /trabalho/este.js/node_modules/bufferutil
gyp ERR! node -v v0.11.13
gyp ERR! node-gyp -v v0.13.0
gyp ERR! not ok 
npm ERR! bufferutil@1.2.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bufferutil@1.2.1 install script.
npm ERR! This is most likely a problem with the bufferutil package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls bufferutil
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 3.16.0-43-generic
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "bufferutil@1.2.1"
npm ERR! cwd /trabalho/este.js
npm ERR! node -v v0.11.13
npm ERR! npm -v 1.4.9
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /trabalho/este.js/npm-debug.log
npm ERR! not ok code 0
```

**Comment by thr0w** [comment]
Problem solved upgrading node

```bash
$ node --version
v5.3.0
$ npm --version
3.3.12
```
