### ISSUE TITLE
node-gyp rebuild fails

### ISSUE THREAD

**Issue by gerardolima** [websockets/bufferutil#40]
```
$ npm install -g bufferutil > stdout.txt
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\gerardo.lima\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:100:13)
gyp ERR! stack     at ChildProcess.emit (events.js:185:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\gerardo.lima\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\gerardo.lima\AppData\Roaming\npm\node_modules\bufferutil
gyp ERR! node -v v5.11.0
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\gerardo.lima\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "bufferutil"
npm ERR! node v5.11.0
npm ERR! npm  v3.8.7
npm ERR! code ELIFECYCLE

npm ERR! bufferutil@1.2.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bufferutil@1.2.1 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the bufferutil package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs bufferutil
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls bufferutil
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\tmp\bufferutil\npm-debug.log
```

[npm-debug.log.txt](https://github.com/websockets/bufferutil/files/237230/npm-debug.log.txt)
[stdout.txt](https://github.com/websockets/bufferutil/files/237231/stdout.txt)

**Comment by nicholaswmin** [comment]
Getting the same when deploying on Heroku

**Comment by Shun2014** [comment]
same issue

**Comment by nicholaswmin** [comment]
For those on Heroku, clear your Heroku cache

**Comment by lpinca** [comment]
Closing this as Node.js 5 is no longer supported. Please reopen if needed.
