### ISSUE TITLE
npm install bufferutil failling

### ISSUE THREAD

**Issue by jonatasteixeira** [websockets/bufferutil#48]
I got the follow error when I tried to install bufferutil:

jonatas@zion:~$ npm install bufferutil

```
> bufferutil@1.2.1 install /home/mobile/stf/node_modules/bufferutil
> node-gyp rebuild

gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: unable to verify the first certificate
gyp ERR! stack     at Error (native)
gyp ERR! stack     at TLSSocket.<anonymous> (_tls_wrap.js:1060:38)
gyp ERR! stack     at emitNone (events.js:86:13)
gyp ERR! stack     at TLSSocket.emit (events.js:185:7)
gyp ERR! stack     at TLSSocket._finishInit (_tls_wrap.js:584:8)
gyp ERR! stack     at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:416:38)
gyp ERR! System Linux 3.16.0-4-amd64
gyp ERR! command "/home/mobile/.nvm/versions/node/v6.3.1/bin/node" "/home/mobile/.nvm/versions/node/v6.3.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/mobile/stf/node_modules/bufferutil
gyp ERR! node -v v6.3.1
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14
npm ERR! Linux 3.16.0-4-amd64
npm ERR! argv "/home/mobile/.nvm/versions/node/v6.3.1/bin/node" "/home/mobile/.nvm/versions/node/v6.3.1/bin/npm" "install" "bufferutil"
npm ERR! node v6.3.1
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE

npm ERR! bufferutil@1.2.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bufferutil@1.2.1 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the bufferutil package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs bufferutil
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls bufferutil
```

Some aditional info:
```
$ nvm version
> v6.3.1
$ node --version
> v6.3.1
$ npm --version
> 3.10.3
$ cat /etc/debian_version 
> 8.5
$ python --version
> Python 2.7.12
```

Someone know whats could it be?

tks

**Comment by jonatasteixeira** [comment]
Hello everybody, 

I figure out how to solve this issue. Its about a proxy of my company.
Its just necessary to disable the ssl check by doing this:

```
npm config set strict-ssl false
NODE_TLS_REJECT_UNAUTHORIZED=0 npm install
```
So, everything is working well! tks ;)
