### ISSUE TITLE
Failed at the bufferutil@1.3.0 install script 'node-gyp rebuild'. 

### ISSUE THREAD

**Issue by daring123** [websockets/bufferutil#65]
HI:
I install "stf" by npm .
my command is "npm install -g stf ". I got wrong.
Here is the error message.Hope to help me solve it .Thanks

65470 verbose pkgid bufferutil@1.3.0
65471 verbose cwd /home/hzqa/wireless
65472 error Linux 3.10.0-514.el7.x86_64
65473 error argv "/home/hzqa/wireless/node-v6.10.0/bin/node" "/home/hzqa/wireless/node-v6.10.0/bin/npm" "install" "-g" "stf"
65474 error node v6.10.0
65475 error npm v3.10.10
65476 error file sh
65477 error code ELIFECYCLE
65478 error errno ENOENT
65479 error syscall spawn
65480 error bufferutil@1.3.0 install: node-gyp rebuild
65480 error spawn ENOENT
65481 error Failed at the bufferutil@1.3.0 install script 'node-gyp rebuild'.
65481 error Make sure you have the latest version of node.js and npm installed.
65481 error If you do, this is most likely a problem with the bufferutil package,
65481 error not with npm itself.
65481 error Tell the author that this fails on your system:
65481 error node-gyp rebuild
65481 error You can get information on how to open an issue for this project with:
65481 error npm bugs bufferutil
65481 error Or if that isn't available, you can get their info via:
65481 error npm owner ls bufferutil
65481 error There is likely additional logging output above.
65482 verbose exit [ 1, true ]

**Comment by lpinca** [comment]
Can you try to use `sudo`?

```
sudo npm install -g stf
```

**Comment by lpinca** [comment]
@daring123 ping.

**Comment by lpinca** [comment]
Closing due to inactivity.

**Comment by abhii2628** [comment]
Hey @lpinca  I am getting the same error while installing stf. Also, I tried doing the same through sudo user but no luck. can you please help with the same ?

npm ERR! Failed at the bufferutil@1.3.0 install script.

**Comment by lpinca** [comment]
Make sure to have a working C++ compiler on your system. They should update both [https://github.com/openstf/stf/blob/029efa80d45013fd48dd782bb3899c5a5ac6c881/package.json#L44](bufferutil) and [https://github.com/openstf/stf/blob/029efa80d45013fd48dd782bb3899c5a5ac6c881/package.json#L93](utf-8-validate) to take advantage of prebuilt binaries.

**Comment by heavy-razzer** [comment]
CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
In file included from ../src/bufferutil.cc:16:
In file included from ../../nan/nan.h:190:
../../nan/nan_maybe_43_inl.h:88:15: error: no member named 'ForceSet' in
      'v8::Object'
  return obj->ForceSet(GetCurrentContext(), key, value, attribs);

4 warnings and 1 error generated.
make: *** [Release/obj.target/bufferutil/src/bufferutil.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:238:12)
gyp ERR! System Darwin 17.7.0
gyp ERR! command "/usr/local/Cellar/node/10.6.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/Cellar/node/10.6.0/lib/node_modules/stf/node_modules/bufferutil
gyp ERR! node -v v10.8.0
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bufferutil@1.3.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bufferutil@1.3.0 install script.

**Comment by lpinca** [comment]
`bufferutil@1.3.0` is outdated, it no longer works in recent versions of Node.js.

**Comment by heavy-razzer** [comment]
So, in this case, how to install stf?
Or this impossible at all at this moment?

**Comment by lpinca** [comment]
I would open a PR to https://github.com/openstf/stf to update it.

**Comment by lpinca** [comment]
As a workaround you could generate  package-lock.json and update the version there, then reinstall so you get an updated version.

**Comment by heavy-razzer** [comment]
@lpinca 
Could you write by steps how to make this? I am new to all this stuff =)

**Comment by lpinca** [comment]
Search on Google you should find examples, sorry I don't have the time to do that.

**Comment by Feliphegomez** [comment]
It should install **Python** and others files.

**Run** this in Windows **PowerShell** as **administrator:**

~~~sh
npm install --global --production windows-build-tools
~~~

**Comment by heavy-razzer** [comment]
Looks like this issue still not fixed. And STF cant be installed on MacOS with commands, described in readme. Very sad.

**Comment by heavy-razzer** [comment]
> It should install **Python** and others files.
> 
> **Run** this in Windows **PowerShell** as **administrator:**
> 
> ```shell
> npm install --global --production windows-build-tools
> ```

STF is for Mac, your command is for Windows.

**Comment by Feliphegomez** [comment]
> > Debe instalar **Python** y otros archivos.
> > **Ejecute** esto en Windows **PowerShell** como **administrador:**
> > ```shell
> > npm install --global --production windows-build-tools
> > ```
> 
> STF es para Mac, su comando es para Windows.

How to Update Node and NPM
New versions of Node and NPM come out frequently. You can use Homebrew to update the software it installs.

Make sure Homebrew has the latest version of the Node package. In Terminal type brew update
Upgrade Node: brew upgrade node

**Comment by cyyber** [comment]
I had the same issue while installing it on Ubuntu 18.04.4

I switched using Node version 6.1.0 and I did install boost libraries by following command
sudo apt-get install libboost-all-dev

After that I was able to install bufferutil@1.3.0

**Comment by greyreality** [comment]
hi)
i managed to install stf on Mac. command "stf local" was working correctly after this.
In Dockerfile stf is using node version 8.9.3. Make sure that you have this version.
` clone stf repo and cd stf
nvm install 8.9.3
npm install jpeg-turbo@0.4.0
npm install bufferutil@1.3.0
npm install bufferutil@4.0.1
npm install utf-8-validate@5.0.2
npm install webpack-dev-server@3.11.0
npm install webpack-dev-middleware@3.7.2
npm i validate-npm-package-license
npm i hosted-git-info
npm i zmq
npm i isexe
npm install -g sass-loader
npm install -g css-loader
npm i are-we-there-yet
npm i gauge
npm rebuild node-sass
stf local
http://localhost:7100/auth/mock/`

**Comment by BiteFoo** [comment]
> hi)
> i managed to install stf on Mac. command "stf local" was working correctly after this.
> In Dockerfile stf is using node version 8.9.3. Make sure that you have this version.
> 
> > clone stf repo and cd stf
> > nvm install 8.9.3
> > npm install jpeg-turbo@0.4.0
> > npm install bufferutil@1.3.0
> > npm install bufferutil@4.0.1
> > npm install utf-8-validate@5.0.2
> > npm install webpack-dev-server@3.11.0
> > npm install webpack-dev-middleware@3.7.2
> > npm i validate-npm-package-license
> > npm i hosted-git-info
> > npm i zmq
> > npm i isexe
> > npm install -g sass-loader
> > npm install -g css-loader
> > npm i are-we-there-yet
> > npm i gauge
> > npm rebuild node-sass
> > stf local
> > http://localhost:7100/auth/mock/

Yes,it's works for me .thx 👍

**Comment by shadab2510** [comment]
> 

Hi @greyreality Thank you for the valuable feed you added here, I was struggling setting up stf in mac , tried with different node versions but no luck, I tried using the steps you mentioned here but just after installing node 8.9.3, and the moment i try install npm install jpeg-turbo@0.4.0, getting the below logs, It would really appreciate if you could help me out 

```
apples-MacBook-Pro:stf-master apple$ node -v
v8.9.3
apples-MacBook-Pro:stf-master apple$ npm install jpeg-turbo@0.4.0

> jpeg-turbo@0.4.0 install /Users/apple/Desktop/STF_latest/stf-master/node_modules/jpeg-turbo
> node-pre-gyp install --fallback-to-build

node-pre-gyp info it worked if it ends with ok
node-pre-gyp verb cli [ '/Users/apple/.nvm/versions/node/v8.9.3/bin/node',
node-pre-gyp verb cli   '/Users/apple/Desktop/STF_latest/stf-master/node_modules/jpeg-turbo/node_modules/.bin/node-pre-gyp',
node-pre-gyp verb cli   'install',
node-pre-gyp verb cli   '--fallback-to-build' ]
node-pre-gyp info using node-pre-gyp@0.6.19
node-pre-gyp info using node@8.9.3 | darwin | x64
node-pre-gyp verb command install []
node-pre-gyp info check checked for "/Users/apple/Desktop/STF_latest/stf-master/node_modules/jpeg-turbo/lib/binding/node-v57-darwin-x64/jpegturbo.node" (not found)
node-pre-gyp http GET https://pre-gyp.s3.amazonaws.com/jpegturbo/v0.4.0/jpegturbo-v0.4.0-node-v57-darwin-x64.tar.gz
node-pre-gyp http 403 https://pre-gyp.s3.amazonaws.com/jpegturbo/v0.4.0/jpegturbo-v0.4.0-node-v57-darwin-x64.tar.gz
node-pre-gyp http 403 status code downloading tarball https://pre-gyp.s3.amazonaws.com/jpegturbo/v0.4.0/jpegturbo-v0.4.0-node-v57-darwin-x64.tar.gz (falling back to source compile with node-gyp) 
node-pre-gyp verb command build [ 'rebuild' ]
gyp ERR! UNCAUGHT EXCEPTION 
gyp ERR! stack /usr/local/lib/node_modules/node-gyp/lib/find-python.js:39
gyp ERR! stack   } catch {}
gyp ERR! stack           ^
gyp ERR! stack 
gyp ERR! stack SyntaxError: Unexpected token {
gyp ERR! stack     at createScript (vm.js:80:10)
gyp ERR! stack     at Object.runInThisContext (vm.js:139:10)
gyp ERR! stack     at Module._compile (module.js:599:28)
gyp ERR! stack     at Object.Module._extensions..js (module.js:646:10)
gyp ERR! stack     at Module.load (module.js:554:32)
gyp ERR! stack     at tryModuleLoad (module.js:497:12)
gyp ERR! stack     at Function.Module._load (module.js:489:3)
gyp ERR! stack     at Module.require (module.js:579:17)
gyp ERR! stack     at require (internal/module.js:11:18)
gyp ERR! stack     at Object.<anonymous> (/usr/local/lib/node_modules/node-gyp/lib/configure.js:11:18)
gyp ERR! System Darwin 19.6.0
gyp ERR! command "/Users/apple/.nvm/versions/node/v8.9.3/bin/node" "/usr/local/lib/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/Users/apple/Desktop/STF_latest/stf-master/node_modules/jpeg-turbo/lib/binding/node-v57-darwin-x64/jpegturbo.node" "--module_name=jpegturbo" "--module_path=/Users/apple/Desktop/STF_latest/stf-master/node_modules/jpeg-turbo/lib/binding/node-v57-darwin-x64"
gyp ERR! cwd /Users/apple/Desktop/STF_latest/stf-master/node_modules/jpeg-turbo
gyp ERR! node -v v8.9.3
gyp ERR! node-gyp -v v8.1.0
gyp ERR! Node-gyp failed to build your package.
gyp ERR! Try to update npm and/or node-gyp and if it does not help file an issue with the package author.
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/Users/apple/.nvm/versions/node/v8.9.3/bin/node /usr/local/lib/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/apple/Desktop/STF_latest/stf-master/node_modules/jpeg-turbo/lib/binding/node-v57-darwin-x64/jpegturbo.node --module_name=jpegturbo --module_path=/Users/apple/Desktop/STF_latest/stf-master/node_modules/jpeg-turbo/lib/binding/node-v57-darwin-x64' (7)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/apple/Desktop/STF_latest/stf-master/node_modules/jpeg-turbo/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:126:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:925:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
node-pre-gyp ERR! System Darwin 19.6.0
node-pre-gyp ERR! command "/Users/apple/.nvm/versions/node/v8.9.3/bin/node" "/Users/apple/Desktop/STF_latest/stf-master/node_modules/jpeg-turbo/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/apple/Desktop/STF_latest/stf-master/node_modules/jpeg-turbo
node-pre-gyp ERR! node -v v8.9.3
node-pre-gyp ERR! node-pre-gyp -v v0.6.19
node-pre-gyp ERR! not ok 
Failed to execute '/Users/apple/.nvm/versions/node/v8.9.3/bin/node /usr/local/lib/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/apple/Desktop/STF_latest/stf-master/node_modules/jpeg-turbo/lib/binding/node-v57-darwin-x64/jpegturbo.node --module_name=jpegturbo --module_path=/Users/apple/Desktop/STF_latest/stf-master/node_modules/jpeg-turbo/lib/binding/node-v57-darwin-x64' (7)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! jpeg-turbo@0.4.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the jpeg-turbo@0.4.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/apple/.npm/_logs/2022-04-02T08_19_45_198Z-debug.log
apples-MacBook-Pro:stf-master apple$ 
```
