### ISSUE TITLE
Need to bump nan to 2.x

### ISSUE THREAD

**Issue by micky2be** [websockets/bufferutil#9]
For compatibility with iojs 3

```bash
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/opt/nvm/versions/io.js/v3.0.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 3.2.0-4-amd64
gyp ERR! command "/opt/nvm/versions/io.js/v3.0.0/bin/iojs" "/opt/nvm/versions/io.js/v3.0.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/vagrant/dofus/node_modules/engine.io/node_modules/ws/node_modules/bufferutil
gyp ERR! node -v v3.0.0
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok
```

**Comment by 3rd-Eden** [comment]
#8

**Comment by micky2be** [comment]
sorry about that

**Comment by 3rd-Eden** [comment]
No worries, just adding references to all the things so bug reports, issues etc are found better.
